version: "3.9"
services:
  web:
    build: .
    image: sandbox
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"

  db:
    image: citusdata/citus
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"

volumes:
  postgresql-data: